version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: logdash-postgres
    environment:
      POSTGRES_DB: logdash_db
      POSTGRES_USER: logdash_user
      POSTGRES_PASSWORD: logdash_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - logdash-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logdash_user -d logdash_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:26.5
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_pass
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - logdash-network

  logdash-backend:
    build: .
    image: logdash-backend:latest
    container_name: logdash-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/logdash_db
      SPRING_DATASOURCE_USERNAME: logdash_user
      SPRING_DATASOURCE_PASSWORD: logdash_pass
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8080/realms/logdash
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/logdash/protocol/openid-connect/certs
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_completed_successfully
    networks:
      - logdash-network

volumes:
  postgres-data:

networks:
  logdash-network:
    driver: bridge
